name: Deploy


on:
  #Events: Trigger for merge event
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest #All jobs are run on Github server not local machine

    steps: ##
    - uses: actions/checkout@v4 #Tells the github to heckout the current branch
    - run: docker build -t spabadmin/github-actions:latest . #it shoulb match with dockerhub repo
    - run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u spabadmin --password-stdin
    - run: docker push spabadmin/github-actions:latest